CLASS zcl_31_eagm_vat_indicator DEFINITION
  PUBLIC
  FINAL
  CREATE PUBLIC .

  PUBLIC SECTION.
    data:
        vat_indicator TYPE string.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS ZCL_31_EAGM_VAT_INDICATOR IMPLEMENTATION.
ENDCLASS.
