CLASS zcl_33_eagm_record DEFINITION INHERITING FROM zcl_32_eagm_constr_cntr
  PUBLIC
  FINAL
  CREATE PUBLIC .

  PUBLIC SECTION.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS ZCL_33_EAGM_RECORD IMPLEMENTATION.
ENDCLASS.
