CLASS zcl_19_eagm_honda DEFINITION ABSTRACT INHERITING FROM zcl_18_eagm_moto
  PUBLIC
  CREATE PUBLIC .

  PUBLIC SECTION.
  PROTECTED SECTION.
    METHODS:
        set_model ABSTRACT EXPORTING ev_model TYPE string.
  PRIVATE SECTION.
ENDCLASS.



CLASS ZCL_19_EAGM_HONDA IMPLEMENTATION.
ENDCLASS.
