CLASS zcl_06_eagm_storage DEFINITION INHERITING FROM zcl_05_eagm_plant
  PUBLIC
  CREATE PUBLIC .

  PUBLIC SECTION.
  PROTECTED SECTION.
  PRIVATE SECTION.

ENDCLASS.



CLASS ZCL_06_EAGM_STORAGE IMPLEMENTATION.
ENDCLASS.
