CLASS zcl_21_eagm_airplane DEFINITION ABSTRACT
  PUBLIC
  CREATE PUBLIC .

  PUBLIC SECTION.
    METHODS:
      airplane_type ABSTRACT RETURNING VALUE(rv_airplane_type) TYPE string..
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS ZCL_21_EAGM_AIRPLANE IMPLEMENTATION.
ENDCLASS.
