CLASS zcl_08_eagm_lion DEFINITION INHERITING FROM zcl_07_eagm_animal
  PUBLIC
  FINAL
  CREATE PUBLIC .

  PUBLIC SECTION.
    METHODS:
      walk REDEFINITION.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS ZCL_08_EAGM_LION IMPLEMENTATION.


  METHOD walk.
    rv_walk = 'The Lion walks'.
  ENDMETHOD.
ENDCLASS.
