CLASS zcl_10_eagm_eu_citizen DEFINITION INHERITING FROM zcl_09_eagm_citizen
  PUBLIC
    FINAL
  CREATE PUBLIC .

  PUBLIC SECTION.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS ZCL_10_EAGM_EU_CITIZEN IMPLEMENTATION.
ENDCLASS.
