CLASS zcx_53_eagm_exception3 DEFINITION
  PUBLIC
  FINAL
  INHERITING FROM cx_static_check
  CREATE PUBLIC .

  PUBLIC SECTION.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS zcx_53_eagm_exception3 IMPLEMENTATION.
ENDCLASS.
