CLASS zcx_52_eagm_exception2 DEFINITION
  PUBLIC
  FINAL
  INHERITING FROM cx_static_check
  CREATE PUBLIC .

  PUBLIC SECTION.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS zcx_52_eagm_exception2 IMPLEMENTATION.
ENDCLASS.
