CLASS zcx_51_eagm_exception1 DEFINITION
  PUBLIC
  FINAL
  INHERITING FROM cx_static_check
  CREATE PUBLIC .

  PUBLIC SECTION.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS zcx_51_eagm_exception1 IMPLEMENTATION.
ENDCLASS.
